from __future__ import annotations

import json
import re

from app.chains.base import load_prompt, run_llm_chat
from app.providers.llm.base import LlmMessage
from app.schemas.guidance import StudyPlanRequest, StudyPlanResponse
from app.security.context import RequestContext
from app.services.mastery import MasteryService


def _parse_plan(content: str) -> dict | None:
    match = re.search(r"\{[\s\S]*\}", content.strip())
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


class StudyPlanChain:
    def __init__(self, mastery: MasteryService | None = None) -> None:
        self._mastery = mastery or MasteryService()

    async def run(self, ctx: RequestContext, payload: StudyPlanRequest) -> StudyPlanResponse:
        signals = payload.student_signals
        student_id = signals.student_id if signals else ctx.actor_id
        self._mastery.rollup_from_signals(tenant_id=ctx.tenant_id, signals=signals)
        mastery_items = self._mastery.list_mastery(
            tenant_id=ctx.tenant_id,
            student_id=student_id,
        )
        signal_block = "No signals provided."
        if signals:
            signal_block = json.dumps(signals.model_dump(by_alias=True), default=str)[:8000]
        mastery_block = json.dumps([m.model_dump(by_alias=True) for m in mastery_items[:20]], default=str)
        system = (
            f"{load_prompt('study_plan')}\n\n"
            f"Student signals:\n{signal_block}\n\n"
            f"Topic mastery:\n{mastery_block}"
        )
        result = await run_llm_chat(
            ctx=ctx,
            system_prompt=system,
            messages=[LlmMessage(role="user", content="Generate my study plan for this week.")],
            provider=payload.provider,
        )
        parsed = _parse_plan(result.content) or {}
        actions = [str(x) for x in parsed.get("actions", []) if str(x).strip()]
        focus = [str(x) for x in parsed.get("focusTopics", []) if str(x).strip()]
        summary = parsed.get("masterySummary") if isinstance(parsed.get("masterySummary"), list) else []
        if not summary and mastery_items:
            summary = [
                {
                    "topicKey": item.topic_key,
                    "masteryPct": item.mastery_pct,
                    "note": "From tutor quizzes and CBT results",
                }
                for item in mastery_items[:5]
            ]
        if not actions:
            actions = ["Revise your weakest topic for 15 minutes tonight."]
        sources = ["ai_topic_mastery"]
        if signals and signals.scheme_topics:
            sources.append("academic_scheme_topics")
        if signals and signals.signals:
            sources.append("cbt_attempts")
        return StudyPlanResponse(
            studentId=student_id,
            actions=actions[:8],
            focusTopics=focus[:6],
            masterySummary=summary[:8],
            sources=sources,
            sourceMode="ai",
            disclaimer=(
                "This study plan is generated by AI using your performance, "
                "attendance signals, scheme of work, and topic mastery."
            ),
        )
