"""Minimal SaaS invoice PDF (no extra deps — pure PDF 1.4 text stream)."""

from __future__ import annotations

from datetime import datetime, timezone


def _escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
    )


def _money(amount_minor: int, currency: str) -> str:
    major = amount_minor / 100.0
    return f"{currency} {major:,.2f}"


def build_invoice_pdf(
    *,
    issuer: str,
    invoice_number: str,
    tenant_name: str,
    tenant_slug: str,
    amount_minor: int,
    currency: str,
    tax_minor: int,
    status: str,
    notes: str,
    period_start: datetime | None,
    period_end: datetime | None,
    due_at: datetime | None,
    paid_at: datetime | None,
) -> bytes:
    issued = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    period = "—"
    if period_start or period_end:
        a = period_start.strftime("%Y-%m-%d") if period_start else "?"
        b = period_end.strftime("%Y-%m-%d") if period_end else "?"
        period = f"{a} → {b}"
    due = due_at.strftime("%Y-%m-%d") if due_at else "—"
    paid = paid_at.strftime("%Y-%m-%d") if paid_at else "—"
    subtotal = amount_minor - tax_minor
    lines = [
        issuer,
        "SaaS Invoice",
        "",
        f"Invoice: {invoice_number}",
        f"Status:  {status}",
        f"Issued:  {issued}",
        f"Bill to: {tenant_name} ({tenant_slug})",
        f"Period:  {period}",
        f"Due:     {due}",
        f"Paid:    {paid}",
        "",
        f"Subtotal: {_money(subtotal, currency)}",
        f"Tax/VAT:  {_money(tax_minor, currency)}",
        f"Total:    {_money(amount_minor, currency)}",
        "",
        f"Notes: {notes or '—'}",
        "",
        "This document is generated by Multi-Academy Control.",
    ]

    # Build content stream (Helvetica, top-down)
    y = 780
    content_parts = ["BT", "/F1 11 Tf", "14 TL", f"50 {y} Td"]
    first = True
    for line in lines:
        esc = _escape(line)
        if first:
            content_parts.append(f"({esc}) Tj")
            first = False
        else:
            content_parts.append("T*")
            content_parts.append(f"({esc}) Tj")
    content_parts.append("ET")
    stream = "\n".join(content_parts).encode("latin-1", errors="replace")

    objects: list[bytes] = []
    objects.append(b"1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n")
    objects.append(b"2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n")
    objects.append(
        b"3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>endobj\n"
    )
    objects.append(
        f"4 0 obj<< /Length {len(stream)} >>stream\n".encode()
        + stream
        + b"\nendstream\nendobj\n"
    )
    objects.append(b"5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n")

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for obj in objects:
        offsets.append(len(out))
        out.extend(obj)
    xref_pos = len(out)
    out.extend(f"xref\n0 {len(offsets)}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode())
    out.extend(
        f"trailer<< /Size {len(offsets)} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n".encode()
    )
    return bytes(out)
