"""phase B/C tables, billing + outbox delivery, tenant scoping

Revision ID: fe907f08ef7b
Revises: fe4c316b8bf0
Create Date: 2026-07-28 07:02:03.722590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe907f08ef7b'
down_revision: Union[str, Sequence[str], None] = 'fe4c316b8bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billing_cycle', sa.String(length=32), nullable=False),
    sa.Column('pricing_model', sa.String(length=32), nullable=False),
    sa.Column('per_student_minor', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('entitlements', sa.JSON(), nullable=True),
    sa.Column('quotas', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dual_control_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('requested_by_id', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by_id', sa.String(length=64), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dual_control_requests_action'), 'dual_control_requests', ['action'], unique=False)
    op.create_index(op.f('ix_dual_control_requests_status'), 'dual_control_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dual_control_requests_target_id'), 'dual_control_requests', ['target_id'], unique=False)
    op.create_table('flag_cohort_rollouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('cohort_tags', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_index(op.f('ix_flag_cohort_rollouts_feature_key'), 'flag_cohort_rollouts', ['feature_key'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('impact', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('affected_components', sa.JSON(), nullable=False),
    sa.Column('updates', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('postmortem_url', sa.String(length=512), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('ip_allowlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidr')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(length=24), nullable=False),
    sa.Column('delivery_log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_delivery_status'), 'outbox_events', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_next_attempt_at'), 'outbox_events', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_published'), 'outbox_events', ['published'], unique=False)
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('ip_allowlist_enforced', sa.Boolean(), nullable=False),
    sa.Column('idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_components_key'), 'status_components', ['key'], unique=True)
    op.create_table('subprocessors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('dpa_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_meters_key'), 'usage_meters', ['key'], unique=True)
    op.create_table('abuse_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_cases_status'), 'abuse_cases', ['status'], unique=False)
    op.create_index(op.f('ix_abuse_cases_tenant_id'), 'abuse_cases', ['tenant_id'], unique=False)
    op.create_table('dsr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=16), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=False),
    sa.Column('export_uri', sa.String(length=512), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_requests_request_type'), 'dsr_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_dsr_requests_status'), 'dsr_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dsr_requests_subject_email'), 'dsr_requests', ['subject_email'], unique=False)
    op.create_index(op.f('ix_dsr_requests_tenant_id'), 'dsr_requests', ['tenant_id'], unique=False)
    op.create_table('provider_failover_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('primary_provider_id', sa.String(length=64), nullable=False),
    sa.Column('secondary_provider_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('is_tripped', sa.Boolean(), nullable=False),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability', 'tenant_id')
    )
    op.create_index(op.f('ix_provider_failover_policies_capability'), 'provider_failover_policies', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_failover_policies_tenant_id'), 'provider_failover_policies', ['tenant_id'], unique=False)
    op.create_table('staff_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_sessions_jti'), 'staff_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_staff_sessions_refresh_jti'), 'staff_sessions', ['refresh_jti'], unique=True)
    op.create_index(op.f('ix_staff_sessions_user_id'), 'staff_sessions', ['user_id'], unique=False)
    op.create_table('support_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('staff_email', sa.String(length=255), nullable=False),
    sa.Column('access_level', sa.String(length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_sessions_is_active'), 'support_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_sessions_tenant_id'), 'support_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_ticket_id'), 'support_sessions', ['ticket_id'], unique=False)
    op.create_table('tenant_offboard_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('export_package_uri', sa.String(length=512), nullable=False),
    sa.Column('wipe_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold_blocked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_offboard_jobs_status'), 'tenant_offboard_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_offboard_jobs_tenant_id'), 'tenant_offboard_jobs', ['tenant_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('meter_key', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_id'), 'usage_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_usage_events_meter_key'), 'usage_events', ['meter_key'], unique=False)
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    op.create_table('usage_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meter_key', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'meter_key', 'period_key')
    )
    op.create_index(op.f('ix_usage_rollups_meter_key'), 'usage_rollups', ['meter_key'], unique=False)
    op.create_index(op.f('ix_usage_rollups_period_key'), 'usage_rollups', ['period_key'], unique=False)
    op.create_index(op.f('ix_usage_rollups_tenant_id'), 'usage_rollups', ['tenant_id'], unique=False)
    op.create_table('abuse_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('auto_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['abuse_cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_signals_case_id'), 'abuse_signals', ['case_id'], unique=False)
    op.create_index(op.f('ix_abuse_signals_signal_type'), 'abuse_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_abuse_signals_tenant_id'), 'abuse_signals', ['tenant_id'], unique=False)
    op.create_table('saas_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('amount_paid_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), nullable=False),
    sa.Column('tax_label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'period_key', name='uq_invoice_subscription_period')
    )
    op.create_index(op.f('ix_saas_invoices_created_at'), 'saas_invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_saas_invoices_number'), 'saas_invoices', ['number'], unique=True)
    op.create_index(op.f('ix_saas_invoices_period_key'), 'saas_invoices', ['period_key'], unique=False)
    op.create_index(op.f('ix_saas_invoices_status'), 'saas_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_saas_invoices_subscription_id'), 'saas_invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_saas_invoices_tenant_id'), 'saas_invoices', ['tenant_id'], unique=False)
    op.create_table('saas_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['saas_invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_payments_created_at'), 'saas_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_saas_payments_idempotency_key'), 'saas_payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_saas_payments_invoice_id'), 'saas_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_saas_payments_provider_reference'), 'saas_payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_saas_payments_tenant_id'), 'saas_payments', ['tenant_id'], unique=False)
    # --- columns added to pre-existing tables -------------------------------
    # NOT NULL columns carry a server_default so the ALTER succeeds on tables
    # that already hold rows. The defaults mirror the model-side defaults.
    op.add_column(
        'feature_flags',
        sa.Column('deprecation_note', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column('feature_flags', sa.Column('removal_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feature_flags', sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column(
        'service_clients',
        sa.Column('allowed_tenant_refs', sa.JSON(), nullable=False, server_default='[]'),
    )
    # Widened for PBKDF2 hashes (pbkdf2_sha256$iterations$salt$digest); legacy
    # 64-char SHA256 values still verify and are rehashed on next successful auth.
    # batch_alter_table so this also runs on SQLite, which has no ALTER COLUMN TYPE.
    with op.batch_alter_table('service_clients') as batch:
        batch.alter_column(
            'secret_hash',
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    op.add_column(
        'subscriptions',
        sa.Column('pricing_model', sa.String(length=32), nullable=False, server_default='flat'),
    )
    op.add_column('subscriptions', sa.Column('per_student_minor', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('student_count', sa.Integer(), nullable=True))
    op.add_column(
        'subscriptions',
        sa.Column('dunning_step', sa.String(length=32), nullable=False, server_default='none'),
    )
    op.add_column('subscriptions', sa.Column('past_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'subscriptions',
        sa.Column('deal_name', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'subscriptions',
        sa.Column('approval_status', sa.String(length=32), nullable=False, server_default='active'),
    )
    op.add_column('subscriptions', sa.Column('next_invoice_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column(
        'tenants',
        sa.Column('status_reason', sa.String(length=32), nullable=False, server_default=''),
    )
    op.add_column(
        'tenants',
        sa.Column('residency_tag', sa.String(length=32), nullable=False, server_default='NG'),
    )
    op.add_column(
        'tenants',
        sa.Column('legal_hold', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'tenants',
        sa.Column('legal_hold_reason', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column('tenants', sa.Column('courtesy_unlock_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tenants_status_reason'), 'tenants', ['status_reason'], unique=False)

    # Existing suspended tenants were marked by matching "saas" in the message;
    # backfill the structured reason so auto-reactivation keeps working for them.
    op.execute(
        """
        UPDATE tenants
           SET status_reason = 'billing_dunning'
         WHERE status = 'suspended'
           AND lower(status_message) LIKE '%saas%'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_status_reason'), table_name='tenants')
    op.drop_column('tenants', 'courtesy_unlock_until')
    op.drop_column('tenants', 'legal_hold_reason')
    op.drop_column('tenants', 'legal_hold')
    op.drop_column('tenants', 'residency_tag')
    op.drop_column('tenants', 'status_reason')
    op.drop_column('subscriptions', 'next_invoice_at')
    op.drop_column('subscriptions', 'approval_status')
    op.drop_column('subscriptions', 'deal_name')
    op.drop_column('subscriptions', 'grace_until')
    op.drop_column('subscriptions', 'past_due_at')
    op.drop_column('subscriptions', 'dunning_step')
    op.drop_column('subscriptions', 'student_count')
    op.drop_column('subscriptions', 'per_student_minor')
    op.drop_column('subscriptions', 'pricing_model')
    # Narrowing back to 64 chars truncates any PBKDF2 hash written since the
    # upgrade, so those clients must have their secrets reissued afterwards.
    with op.batch_alter_table('service_clients') as batch:
        batch.alter_column(
            'secret_hash',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
    op.drop_column('service_clients', 'allowed_tenant_refs')
    op.drop_column('feature_flags', 'deprecated_at')
    op.drop_column('feature_flags', 'removal_date')
    op.drop_column('feature_flags', 'deprecation_note')
    op.drop_index(op.f('ix_saas_payments_tenant_id'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_provider_reference'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_invoice_id'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_idempotency_key'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_created_at'), table_name='saas_payments')
    op.drop_table('saas_payments')
    op.drop_index(op.f('ix_saas_invoices_tenant_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_subscription_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_status'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_period_key'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_number'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_created_at'), table_name='saas_invoices')
    op.drop_table('saas_invoices')
    op.drop_index(op.f('ix_abuse_signals_tenant_id'), table_name='abuse_signals')
    op.drop_index(op.f('ix_abuse_signals_signal_type'), table_name='abuse_signals')
    op.drop_index(op.f('ix_abuse_signals_case_id'), table_name='abuse_signals')
    op.drop_table('abuse_signals')
    op.drop_index(op.f('ix_usage_rollups_tenant_id'), table_name='usage_rollups')
    op.drop_index(op.f('ix_usage_rollups_period_key'), table_name='usage_rollups')
    op.drop_index(op.f('ix_usage_rollups_meter_key'), table_name='usage_rollups')
    op.drop_table('usage_rollups')
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_meter_key'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_tenant_offboard_jobs_tenant_id'), table_name='tenant_offboard_jobs')
    op.drop_index(op.f('ix_tenant_offboard_jobs_status'), table_name='tenant_offboard_jobs')
    op.drop_table('tenant_offboard_jobs')
    op.drop_index(op.f('ix_support_sessions_ticket_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_tenant_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_is_active'), table_name='support_sessions')
    op.drop_table('support_sessions')
    op.drop_index(op.f('ix_staff_sessions_user_id'), table_name='staff_sessions')
    op.drop_index(op.f('ix_staff_sessions_refresh_jti'), table_name='staff_sessions')
    op.drop_index(op.f('ix_staff_sessions_jti'), table_name='staff_sessions')
    op.drop_table('staff_sessions')
    op.drop_index(op.f('ix_provider_failover_policies_tenant_id'), table_name='provider_failover_policies')
    op.drop_index(op.f('ix_provider_failover_policies_capability'), table_name='provider_failover_policies')
    op.drop_table('provider_failover_policies')
    op.drop_index(op.f('ix_dsr_requests_tenant_id'), table_name='dsr_requests')
    op.drop_index(op.f('ix_dsr_requests_subject_email'), table_name='dsr_requests')
    op.drop_index(op.f('ix_dsr_requests_status'), table_name='dsr_requests')
    op.drop_index(op.f('ix_dsr_requests_request_type'), table_name='dsr_requests')
    op.drop_table('dsr_requests')
    op.drop_index(op.f('ix_abuse_cases_tenant_id'), table_name='abuse_cases')
    op.drop_index(op.f('ix_abuse_cases_status'), table_name='abuse_cases')
    op.drop_table('abuse_cases')
    op.drop_index(op.f('ix_usage_meters_key'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_table('subprocessors')
    op.drop_index(op.f('ix_status_components_key'), table_name='status_components')
    op.drop_table('status_components')
    op.drop_table('security_settings')
    op.drop_index(op.f('ix_outbox_events_published'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_next_attempt_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_delivery_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('ip_allowlist_entries')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_flag_cohort_rollouts_feature_key'), table_name='flag_cohort_rollouts')
    op.drop_table('flag_cohort_rollouts')
    op.drop_index(op.f('ix_dual_control_requests_target_id'), table_name='dual_control_requests')
    op.drop_index(op.f('ix_dual_control_requests_status'), table_name='dual_control_requests')
    op.drop_index(op.f('ix_dual_control_requests_action'), table_name='dual_control_requests')
    op.drop_table('dual_control_requests')
    op.drop_table('deal_templates')
    # ### end Alembic commands ###
