import { IsEmail, IsOptional, IsString, MinLength } from 'class-validator';

export class RegisterStep1Dto {
  @IsString()
  @MinLength(2)
  fullName!: string;

  @IsEmail()
  email!: string;

  @IsString()
  @MinLength(8)
  password!: string;

  @IsOptional()
  @IsString()
  phone?: string;

  /** Stable browser-install token generated by the public client. */
  @IsOptional()
  @IsString()
  @MinLength(16)
  installToken?: string;

  /** Privacy-safe client device signal; never persist the raw signal. */
  @IsOptional()
  @IsString()
  @MinLength(16)
  deviceHash?: string;
}
